homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.7981
  longitude: -84.3877
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 289
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize:
    input_boolean.lights_on:
      emulated_hue_name: "Lights"
    input_boolean.lights_off:
      emulated_hue_name: "Dark"
    input_boolean.lights_rave:
      emulated_hue_name: "The Party"
    input_boolean.lights_rainbow:
      emulated_hue_name: "Rainbow"
    input_boolean.lights_confetti:
      emulated_hue_name: "Confetti"
    input_boolean.lights_juggle:
      emulated_hue_name: "Juggling"

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

group: !include groups.yaml

# Amazon Echo
emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - group
    - input_boolean
    - media_player

# Command to turn lights on
rest_command:
  lights_on:
    url: 'http://192.168.1.129:8081/api/AllOn'
  lights_off:
    url: 'http://192.168.1.129:8081/api/AllOff'
  lights_rave:
    url: 'http://192.168.1.129:8081/api/Sound-FHT'
  lights_rainbow:
    url: 'http://192.168.1.129:8081/api/Rainbow'
  lights_juggle:
    url: 'http://192.168.1.129:8081/api/Juggle'
  lights_confetti:
    url: 'http://192.168.1.129:8081/api/Confetti'

# Boolean for calling the above with Alexa
input_boolean:
  lights_on:
    name: The Light
    initial: off
  lights_off:
    name: The Dark
    initial: on
  lights_rave:
    name: The Party
    initial: off
  lights_rainbow:
    name: Rainbow
    initial: off
  lights_confetti:
    name: Confetti
    initial: off
  lights_juggle:
    name: Juggle
    initial: off

# Automation for the above
automation:
  - alias: Turn lights on
    trigger:
      platform: state
      entity_id: input_boolean.lights_on
      to: 'on'
    action:
      - service: rest_command.lights_on
      #- service: input_boolean.turn_off
      #  data:
      #    entity_id: input_boolean.lights_on
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rainbow
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_confetti
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_juggle

  - alias: Turn lights off
    trigger:
      platform: state
      entity_id: input_boolean.lights_off
      to: 'on'
    action:
      - service: rest_command.lights_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_on
      #- service: input_boolean.turn_off
      #  data:
      #    entity_id: input_boolean.lights_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rainbow
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_confetti
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_juggle

  - alias: Turn lights to rave mode
    trigger:
      platform: state
      entity_id: input_boolean.lights_rave
      to: 'on'
    action:
      - service: rest_command.lights_rave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_on
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_off
      #- service: input_boolean.turn_off
      #  data:
      #    entity_id: input_boolean.lights_rave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rainbow
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_confetti
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_juggle

  - alias: Turn lights to rainbow mode
    trigger:
      platform: state
      entity_id: input_boolean.lights_rainbow
      to: 'on'
    action:
      - service: rest_command.lights_rainbow
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_on
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rave
      #- service: input_boolean.turn_off
      #  data:
      #    entity_id: input_boolean.lights_rainbow
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_confetti
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_juggle

  - alias: Turn lights to confetti mode
    trigger:
      platform: state
      entity_id: input_boolean.lights_confetti
      to: 'on'
    action:
      - service: rest_command.lights_confetti
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_on
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rainbow
      #- service: input_boolean.turn_off
      #  data:
      #    entity_id: input_boolean.lights_confetti
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_juggle

  - alias: Turn lights to juggle mode
    trigger:
      platform: state
      entity_id: input_boolean.lights_juggle
      to: 'on'
    action:
      - service: rest_command.lights_juggle
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_on
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_off
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_rainbow
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lights_confetti
      #- service: input_boolean.turn_off
      #  data:
      #    entity_id: input_boolean.lights_juggle
